management:
  endpoints:
    web:
      base-path: /

spring:
  data:
    mongodb:
      database: contacts
      uri: mongodb://${MONGO_HOST:localhost:27017}/contacts?serverSelectionTimeoutMS=2000&connectTimeoutMS=2000