management:
  endpoints:
    web:
      base-path: /

spring:
  data:
    mongodb:
      database: contacts
      uri: mongodb://${MONGO_HOST:localhost:27017}/contacts?serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
  mail:
    host: smtp.gmail.com
    password: NctkgDB&WeW7M5Ks
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000
    username: allanweberdevtests

application:
  verification-url: http://localhost:8080/registration/verify/email

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
